/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.gson.Gson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) throws IOException {
        Quotes[] quotes = gsonify("src/main/resources/happyFile.json");
        int indici = (int)(Math.random()*quotes.length);
        System.out.println(quotes[indici].toString());
    }

        public static Quotes[] gsonify(String filePath) throws IOException {
            // intermediary for json parsing
            Gson gson = new Gson();
//            save json file as string format
            String quoteFile = new String(Files.readAllBytes(Paths.get(filePath)));
//          Convert string into objects and store into quote array
            Quotes[] quoteArr = gson.fromJson(quoteFile, Quotes[].class);
            return quoteArr;
    }

        public static Quotes random(Quotes[] arr){
            int indici = (int)(Math.random()*arr.length);
            return arr[indici];
        }
}
